### ISSUE TITLE
setting up compute workers

### ISSUE THREAD

**Issue by magrichard** [codalab/competitions-v2#566]
Hello,

We tried to connect a worker to a customized queue (deconbench_queue) using the broker URL generated with the queue.
We used the following docker command lines (an image was successfully created on the compute worker):

`docker run \`
      ` -v /var/run/docker.sock:/var/run/docker.sock \`
      ` --env BROKER_URL=pyamqp://6026cf27-3874-481b-bfea-f872113bafc7:0871bef4-38ed-480d-9418-2838dc54e213@134.158.75.165:9001/7637c652-f390-48e1-b68a-95efd99bff96\`
        `-d \`
       `--restart unless-stopped \`
        `--log-opt max-size=1m \`
        `--log-opt max-file=3 \`
        `codalab/competitions-v2-compute-worker`

We set up the queue on the online form of the competition 181 (see below).
![Capture d’écran 2020-11-13 à 15 31 25](https://user-images.githubusercontent.com/18577578/99083487-ea065280-25c5-11eb-9a10-c0cc4e5fcb97.png)

We tried to make submissions, but nothing append (i.e. no ingestion).

Our worry is that our VM machine (located on the deNBI cloud) is not directly accessible from outside. 

Do you have an idea how we could check the connection between the queue and the worker?

**Comment by ckcollab** [comment]
What are the logs from that docker container? You can do something like..

```bash
$ docker ps
# grab the container ID from the above command's output

$ docker logs -f <container ID>
```

**Comment by ashwini-kr-sharma** [comment]
@ckcollab the logs from the docker container shows the following error message recurringly -

`Trying to reconnect...

[2020-11-16 23:22:58,328: ERROR/MainProcess] consumer: Cannot connect to amqp://6026cf27-3874-481b-bfea-f872113bafc7:**@134.158.75.165:9001/7637c652-f390-48e1-b68a-95efd99bff96-d: Connection.open: (530) NOT_ALLOWED - access to vhost '7637c652-f390-48e1-b68a-95efd99bff96-d' refused for user '6026cf27-3874-481b-bfea-f872113bafc7'.
Trying to reconnect...

[2020-11-16 23:22:58,458: ERROR/MainProcess] consumer: Cannot connect to amqp://6026cf27-3874-481b-bfea-f872113bafc7:**@134.158.75.165:9001/7637c652-f390-48e1-b68a-95efd99bff96-d: Connection.open: (530) NOT_ALLOWED - access to vhost '7637c652-f390-48e1-b68a-95efd99bff96-d' refused for user '6026cf27-3874-481b-bfea-f872113bafc7'.
Trying to reconnect...

[2020-11-16 23:22:58,591: ERROR/MainProcess] consumer: Cannot connect to amqp://6026cf27-3874-481b-bfea-f872113bafc7:**@134.158.75.165:9001/7637c652-f390-48e1-b68a-95efd99bff96-d: Connection.open: (530) NOT_ALLOWED - access to vhost '7637c652-f390-48e1-b68a-95efd99bff96-d' refused for user '6026cf27-3874-481b-bfea-f872113bafc7'.
Trying to reconnect...

[2020-11-16 23:22:58,720: ERROR/MainProcess] consumer: Cannot connect to amqp://6026cf27-3874-481b-bfea-f872113bafc7:**@134.158.75.165:9001/7637c652-f390-48e1-b68a-95efd99bff96-d: Connection.open: (530) NOT_ALLOWED - access to vhost '7637c652-f390-48e1-b68a-95efd99bff96-d' refused for user '6026cf27-3874-481b-bfea-f872113bafc7'.
Trying to reconnect...

[2020-11-16 23:22:58,721: CRITICAL/MainProcess] Frequent restarts detected: RestartFreqExceeded('5 in 1s')
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/celery/worker/consumer/consumer.py", line 312, in start
    self._restart_state.step()
  File "/usr/local/lib/python3.8/site-packages/billiard/common.py", line 165, in step
    raise self.RestartFreqExceeded("%r in %rs" % (R, self.maxT))
billiard.exceptions.RestartFreqExceeded: 5 in 1s
`

**Comment by ckcollab** [comment]
Ah, from the new RabbitMQ server we don't have the old credentials. I purged existing queues, could you remake the queue and try again with the new queue url? Tested this process again from scratch and it worked, so it _should be_ working now.
